services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./backend/staticfiles:/staticfile
    depends_on:
      - backend1
      - backend2
      - backend3

  backend1:
    build: ./backend
    environment:
      - PORT=5001
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DB_HOST=db
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app  # Добавляем том
      - ./backend/static:/app/static
      - ./backend/staticfiles:/app/staticfiles
    depends_on:
      - db

  backend2:
    build: ./backend
    environment:
      - PORT=5002
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DB_HOST=db
    ports:
      - "5002:5002"
    volumes:
      - ./backend:/app  # Добавляем том
      - ./backend/static:/app/static
      - ./backend/staticfiles:/app/staticfiles
    depends_on:
      - db

  backend3:
    build: ./backend
    environment:
      - PORT=5003
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DB_HOST=db
    ports:
      - "5003:5003"
    volumes:
      - ./backend:/app  # Добавляем том
      - ./backend/static:/app/static
      - ./backend/staticfiles:/app/staticfiles
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
